"""Preprocessing parameters for ser experiment."""
design_name = 'SVtotal_SVdiff'
contrasts = [('decision',['high','low'],[1,1]),
('neg_decision',['high','low'],[-1,-1]),
('high',['high'],[1]),
('neg_high',['high'],[-1]),
('low',['low'],[1]),
('neg_low',['low'],[-1]),
('low_SV_diff',['low_SV_diff'],[1]),
('neg_low_SV_diff',['low_SV_diff'],[-1]),
('high_SV_diff',['high_SV_diff'],[1]),
('SV_diff',['high_SV_diff','low_SV_diff'],[1,1]),
('neg_SV_diff',['high_SV_diff','low_SV_diff'],[-1,-1]),
('high_minus_low_SV_diff',['high_SV_diff','low_SV_diff'],[1,-1]),
('low_minus_high_SV_diff',['high_SV_diff','low_SV_diff'],[-1,1]),
('high_minus_low',['high','low'],[1,-1]),
('low_minus_high',['high','low'],[-1,1]),
('high_SV_total',['high_SV_total'],[1]),
('neg_high_SV_total',['high_SV_total'],[-1]),
('low_SV_total',['low_SV_total'],[1]),
('neg_low_SV_total',['low_SV_total'],[-1]),
('SV_total',['high_SV_total','low_SV_total'],[1,1]),
('high_minus_low_SV',['high_SV_total','low_SV_total'],[1,-1]),
('low_minus_high_SV',['high_SV_total','low_SV_total'],[-1,1])]